In [1]:
import numpy as np
import pandas as pd
from sklearn.cluster import KMeans
from sklearn import metrics 

In [2]:
#导入数据

In [3]:
df1 =pd.read_csv('C:\\Users\\Tianh\\Desktop\\DMLab\\data\\wineequality\\winequality-white.csv',delimiter=';')

In [4]:
df1.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6  
3      9.9        6  
4      9.9        6

In [5]:
type(df1)

pandas.core.frame.DataFrame

In [8]:
true_label = df1['quality']
true_label = np.array(true_label)
fea = df1.drop('quality',axis=1)
fea = np.array(fea)

In [9]:
res = np.unique(fea)
res

array([0.000e+00, 9.000e-03, 1.000e-02, ..., 3.440e+02, 3.665e+02,
       4.400e+02])

In [10]:
fea

array([[ 7.  ,  0.27,  0.36, ...,  3.  ,  0.45,  8.8 ],
       [ 6.3 ,  0.3 ,  0.34, ...,  3.3 ,  0.49,  9.5 ],
       [ 8.1 ,  0.28,  0.4 , ...,  3.26,  0.44, 10.1 ],
       ...,
       [ 6.5 ,  0.24,  0.19, ...,  2.99,  0.46,  9.4 ],
       [ 5.5 ,  0.29,  0.3 , ...,  3.34,  0.38, 12.8 ],
       [ 6.  ,  0.21,  0.38, ...,  3.26,  0.32, 11.8 ]])

In [11]:
#对数据进行归一化

In [12]:
#最大最小值归一化
# 参考博客：https://blog.csdn.net/zlzl8885/article/details/78094366
def minmax_Norm(dataSet):
    minVals = dataSet.min(0) # 取每一列的最小值
    maxVals = dataSet.max(0) # 取每一列的最大值
    ranges = maxVals - minVals
    normDataSet = np.zeros(np.shape(dataSet))
    m = dataSet.shape[0]
    normDataSet = dataSet - np.tile(minVals, (m, 1))
    normDataSet = normDataSet/np.tile(ranges, (m, 1))   
    return normDataSet

# Z-score归一化
# 参考博客：https://blog.csdn.net/sinat_36458870/article/details/79498302#2Zscore_22
def ZScore_Norm(dataSet):  
    mu = dataSet.average()
    sigma = dataSet.std()
    x = (x - mu) / sigma
    return datsSet  

# Sigmoid归一化
# Sigmoid函数是一个具有S形曲线的函数，
# 是良好的阈值函数，在(0, 0.5)处中心对称，
# 在(0, 0.5)附近有比较大的斜率而当数据趋向于正无穷和负无穷的时候，
# 映射出来的值就会无限趋向于1和0
def sigmoid_Norm(dataSet,useStatus):  
    if useStatus:  
        return 1.0 / (1 + np.exp(-float(dataSet)))
    else:  
        return float(dataSet)
# useStatus管理是否使用sigmoid的状态，方便调试使用

In [13]:
norm_fea = minmax_Norm(fea)
norm_fea

array([[0.30769231, 0.18627451, 0.21686747, ..., 0.25454545, 0.26744186,
        0.12903226],
       [0.24038462, 0.21568627, 0.20481928, ..., 0.52727273, 0.31395349,
        0.24193548],
       [0.41346154, 0.19607843, 0.24096386, ..., 0.49090909, 0.25581395,
        0.33870968],
       ...,
       [0.25961538, 0.15686275, 0.11445783, ..., 0.24545455, 0.27906977,
        0.22580645],
       [0.16346154, 0.20588235, 0.18072289, ..., 0.56363636, 0.18604651,
        0.77419355],
       [0.21153846, 0.12745098, 0.22891566, ..., 0.49090909, 0.11627907,
        0.61290323]])

In [14]:
#k-means 聚类

In [15]:
cluster_num = 6
kmeans = KMeans(n_clusters=cluster_num, random_state=0).fit(fea)
predict_label  =kmeans.labels_
kmeans.cluster_centers_

array([[6.94590793e+00, 2.88228900e-01, 3.50000000e-01, 8.95716113e+00,
        5.17979540e-02, 4.82563939e+01, 1.84991049e+02, 9.96022231e-01,
        3.18732737e+00, 5.13235294e-01, 9.79341432e+00],
       [6.81714406e+00, 2.76701769e-01, 3.26705981e-01, 5.64987363e+00,
        4.38534120e-02, 3.05842460e+01, 1.26997894e+02, 9.93461276e-01,
        3.19174389e+00, 4.84717776e-01, 1.07318169e+01],
       [7.02258065e+00, 3.07111437e-01, 3.60058651e-01, 1.02124633e+01,
        5.18651026e-02, 5.57609971e+01, 2.24640762e+02, 9.96910235e-01,
        3.17284457e+00, 5.20351906e-01, 9.51906158e+00],
       [6.89093432e+00, 2.74384829e-01, 3.44819611e-01, 7.52317299e+00,
        4.85596670e-02, 4.13469010e+01, 1.54589732e+02, 9.94892562e-01,
        3.19296022e+00, 4.88177613e-01, 1.01981314e+01],
       [6.83371824e+00, 2.83106236e-01, 3.12124711e-01, 3.19122402e+00,
        3.90508083e-02, 1.56905312e+01, 6.91270208e+01, 9.91767564e-01,
        3.17002309e+00, 4.68845266e-01, 1.12215550e+

In [16]:
#聚类评价

In [18]:
#Mutual Information based scores 互信息
print(metrics.adjusted_mutual_info_score(true_label,predict_label))

# Homogeneity 同质性 每个群集只包含单个类的成员
print(metrics.homogeneity_score(true_label, predict_label))

# completeness 完整性 类的所有成员都分配给同一个群集
print(metrics.completeness_score(true_label, predict_label))

# 两者的调和平均V-measure：
print(metrics.v_measure_score(true_label, predict_label))

#  Fowlkes-Mallows scores
# The Fowlkes-Mallows score FMI is defined as the geometric mean 
# of the pairwise precision and recall:
print(metrics.fowlkes_mallows_score(true_label,predict_label))

# Silhouette Coefficient 轮廓系数
print(metrics.silhouette_score(fea, predict_label, metric='euclidean'))

# Calinski-Harabaz Index 分数值ss越大则聚类效果越好
# 类别内部数据的协方差越小越好，
# 类别之间的协方差越大越好，这样的Calinski-Harabasz分数会高。
print(metrics.calinski_harabaz_score(fea, predict_label))

D:\Users\Tianh\Anaconda3\lib\site-packages\sklearn\metrics\cluster\supervised.py:746: FutureWarning: The behavior of AMI will change in version 0.22. To match the behavior of 'v_measure_score', AMI will use average_method='arithmetic' by default.
  FutureWarning)


0.02322766277086908
0.033064399703492175
0.025061306985284287
0.02851189666183834
0.26024411228162164
0.3130308350017599
5607.269362493384


D:\Users\Tianh\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:85: DeprecationWarning: Function calinski_harabaz_score is deprecated; Function 'calinski_harabaz_score' has been renamed to 'calinski_harabasz_score' and will be removed in version 0.23.
  warnings.warn(msg, category=DeprecationWarning)
