In [51]:
import numpy as np
import pandas as pd
from sklearn.cluster import KMeans
from sklearn import metrics 

In [52]:
#导入数据

In [21]:
df1 =pd.read_csv('C:\\Users\\Tianh\\Desktop\\DMLab\\data\\wineequality\\winequality-red.csv',delimiter=';')

In [33]:
df1.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [23]:
type(df1)

pandas.core.frame.DataFrame

In [54]:
true_label = df1['quality']
true_label = np.array(true_label)
fea = df1.drop('quality',axis=1)
fea = np.array(fea)

In [42]:
res = np.unique(fea)
res

array([3, 4, 5, 6, 7, 8], dtype=int64)

In [46]:
fea

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
5               7.4             0.660         0.00             1.8      0.075   
6               7.9             0.600         0.06             1.6      0.069   
7               7.3             0.650         0.00             1.2      0.065   
8               7.8             0.580         0.02             2.0      0.073   
9               7.5             0.500         0.36             6.1      0.071   
10              6.7             0.580         0.08             1.8      0.097   
11              7.5             0.500         0.36             6.1      0.071   
12              5.6             0.615         0.00             1.6      0.089   
13              7.8             0.610         0.29             1.6      0.114   
14              8.9             0.620         0.18             3.8      0.176   
15              8.9             0.620         0.19             3.9      0.170   
16              8.5             0.280         0.56             1.8      0.092   
17              8.1             0.560         0.28             1.7      0.368   
18              7.4             0.590         0.08             4.4      0.086   
19              7.9             0.320         0.51             1.8      0.341   
20              8.9             0.220         0.48             1.8      0.077   
21              7.6             0.390         0.31             2.3      0.082   
22              7.9             0.430         0.21             1.6      0.106   
23              8.5             0.490         0.11             2.3      0.084   
24              6.9             0.400         0.14             2.4      0.085   
25              6.3             0.390         0.16             1.4      0.080   
26              7.6             0.410         0.24             1.8      0.080   
27              7.9             0.430         0.21             1.6      0.106   
28              7.1             0.710         0.00             1.9      0.080   
29              7.8             0.645         0.00             2.0      0.082   
...             ...               ...          ...             ...        ...   
1569            6.2             0.510         0.14             1.9      0.056   
1570            6.4             0.360         0.53             2.2      0.230   
1571            6.4             0.380         0.14             2.2      0.038   
1572            7.3             0.690         0.32             2.2      0.069   
1573            6.0             0.580         0.20             2.4      0.075   
1574            5.6             0.310         0.78            13.9      0.074   
1575            7.5             0.520         0.40             2.2      0.060   
1576            8.0             0.300         0.63             1.6      0.081   
1577            6.2             0.700         0.15             5.1      0.076   
1578            6.8             0.670         0.15             1.8      0.118   
1579            6.2             0.560         0.09             1.7      0.053   
1580            7.4             0.350         0.33             2.4      0.068   
1581            6.2             0.560         0.09             1.7      0.053   
1582            6.1             0.715         0.10             2.6      0.053   
1583            6.2             0.460         0.29             2.1      0.074   
1584            6.7             0.320         0.44             2.4      0.061   
1585            7.2             0.390         0.44             2.6      0.066   
1586            7.5             0.310

In [25]:
#对数据进行归一化

In [26]:
#最大最小值归一化
# 参考博客：https://blog.csdn.net/zlzl8885/article/details/78094366
def minmax_Norm(dataSet):
    minVals = dataSet.min(0) # 取每一列的最小值
    maxVals = dataSet.max(0) # 取每一列的最大值
    ranges = maxVals - minVals
    normDataSet = np.zeros(np.shape(dataSet))
    m = dataSet.shape[0]
    normDataSet = dataSet - np.tile(minVals, (m, 1))
    normDataSet = normDataSet/np.tile(ranges, (m, 1))   
    return normDataSet

# Z-score归一化
# 参考博客：https://blog.csdn.net/sinat_36458870/article/details/79498302#2Zscore_22
def ZScore_Norm(dataSet):  
    mu = dataSet.average()
    sigma = dataSet.std()
    x = (x - mu) / sigma
    return datsSet  

# Sigmoid归一化
# Sigmoid函数是一个具有S形曲线的函数，
# 是良好的阈值函数，在(0, 0.5)处中心对称，
# 在(0, 0.5)附近有比较大的斜率而当数据趋向于正无穷和负无穷的时候，
# 映射出来的值就会无限趋向于1和0
def sigmoid_Norm(dataSet,useStatus):  
    if useStatus:  
        return 1.0 / (1 + np.exp(-float(dataSet)))
    else:  
        return float(dataSet)
# useStatus管理是否使用sigmoid的状态，方便调试使用

In [31]:
norm_fea = minmax_Norm(fea)
norm_fea

array([[0.4, 0.4, 0.4, ..., 0.6, 0.4, 0.6],
       [0.4, 0.4, 0.4, ..., 0.6, 0.4, 0.6],
       [0.4, 0.4, 0.4, ..., 0.6, 0.4, 0.6],
       ...,
       [0.4, 0.4, 0.4, ..., 0.6, 0.4, 0.6],
       [0.4, 0.4, 0.4, ..., 0.6, 0.4, 0.6],
       [0.4, 0.4, 0.4, ..., 0.6, 0.4, 0.6]])

In [ ]:
#k-means 聚类

In [48]:
cluster_num = 6
kmeans = KMeans(n_clusters=cluster_num, random_state=0).fit(fea)
predict_label  =kmeans.labels_
kmeans.cluster_centers_

array([[8.23068966e+00, 5.19724138e-01, 2.75896552e-01, 2.40775862e+00,
        9.50482759e-02, 2.50068966e+01, 6.16965517e+01, 9.96898138e-01,
        3.32413793e+00, 6.85206897e-01, 1.02995977e+01],
       [8.62107023e+00, 5.12959866e-01, 2.87575251e-01, 2.42525084e+00,
        8.40217391e-02, 7.47826087e+00, 1.84899666e+01, 9.96637408e-01,
        3.29968227e+00, 6.53795987e-01, 1.06422520e+01],
       [8.02054795e+00, 5.64178082e-01, 3.10684932e-01, 3.27123288e+00,
        9.05890411e-02, 3.16095890e+01, 1.33205479e+02, 9.97217534e-01,
        3.24547945e+00, 7.08767123e-01, 9.76164384e+00],
       [8.23236607e+00, 5.26808036e-01, 2.41830357e-01, 2.39598214e+00,
        8.64441964e-02, 1.54743304e+01, 3.89553571e+01, 9.96687121e-01,
        3.32897321e+00, 6.47700893e-01, 1.04436384e+01],
       [7.82659574e+00, 5.78297872e-01, 2.60265957e-01, 3.09680851e+00,
        8.83510638e-02, 2.31117021e+01, 9.36702128e+01, 9.96857872e-01,
        3.31351064e+00, 6.37074468e-01, 1.01034574e+

In [49]:
#聚类评价

In [55]:
#Mutual Information based scores 互信息
print(metrics.adjusted_mutual_info_score(true_label,predict_label))

# Homogeneity 同质性 每个群集只包含单个类的成员
print(metrics.homogeneity_score(true_label, predict_label))

# completeness 完整性 类的所有成员都分配给同一个群集
print(metrics.completeness_score(true_label, predict_label))

# 两者的调和平均V-measure：
print(metrics.v_measure_score(true_label, predict_label))

#  Fowlkes-Mallows scores
# The Fowlkes-Mallows score FMI is defined as the geometric mean 
# of the pairwise precision and recall:
print(metrics.fowlkes_mallows_score(true_label,predict_label))

# Silhouette Coefficient 轮廓系数
print(metrics.silhouette_score(fea, predict_label, metric='euclidean'))

# Calinski-Harabaz Index 分数值ss越大则聚类效果越好
# 类别内部数据的协方差越小越好，
# 类别之间的协方差越大越好，这样的Calinski-Harabasz分数会高。
print(metrics.calinski_harabaz_score(fea, predict_label))

0.03295680066485905
0.046075171219752374
0.03803161005323997
0.04166876721338937
0.30467978277538565
0.44850222651946337
3120.3770771381646


D:\Users\Tianh\Anaconda3\lib\site-packages\sklearn\metrics\cluster\supervised.py:746: FutureWarning: The behavior of AMI will change in version 0.22. To match the behavior of 'v_measure_score', AMI will use average_method='arithmetic' by default.
  FutureWarning)
D:\Users\Tianh\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:85: DeprecationWarning: Function calinski_harabaz_score is deprecated; Function 'calinski_harabaz_score' has been renamed to 'calinski_harabasz_score' and will be removed in version 0.23.
  warnings.warn(msg, category=DeprecationWarning)
