In [65]:
import pandas as pd
import numpy as np

In [4]:
from sklearn.datasets import load_iris

In [52]:
iris=load_iris()

In [53]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [54]:
print(type(iris.data))

<class 'numpy.ndarray'>


In [62]:
iris_1 = iris.data[:,0]
iris_2 = iris.data[:,1]
iris_3 = iris.data[:,2]
iris_4 = iris.data[:,3]

In [63]:
iris_1 = list(iris_1)
iris_2 = list(iris_2)
iris_3 = list(iris_3)
iris_4 = list(iris_4)

In [71]:
x1 = np.percentile(iris_1,(25,50,75))
x2 = np.percentile(iris_2,(25,50,75))
x3 = np.percentile(iris_3,(25,50,75))
x4 = np.percentile(iris_4,(25,50,75))

In [72]:
print(x1)
print(x2)
print(x3)
print(x4)

[5.1 5.8 6.4]
[2.8 3.  3.3]
[1.6  4.35 5.1 ]
[0.3 1.3 1.8]
